apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: app
type: Opaque
stringData:
  JWT_SECRET: "changeme"
  DB_USERNAME: "root"
  DB_PASSWORD: "changeme"
  DB_NAME: "KSR"
  ADMIN_EMAIL: "admin@ticketflow.local"
  ADMIN_PASSWORD: "changeme"
  ADMIN_NAME: "Admin"