apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/baha0x13/ticket-sale-api-service
    newTag: dad26c6c803ae809cf8996e76d93c8458d96d4fa
  - name: ghcr.io/baha0x13/ticket-sale-auth-service
    newTag: dad26c6c803ae809cf8996e76d93c8458d96d4fa
  - name: ghcr.io/baha0x13/ticket-sale-movie-service
    newTag: dad26c6c803ae809cf8996e76d93c8458d96d4fa
  - name: ghcr.io/baha0x13/ticket-sale-notifications-service
    newTag: dad26c6c803ae809cf8996e76d93c8458d96d4fa
  - name: ghcr.io/baha0x13/ticket-sale-frontend
    newTag: dad26c6c803ae809cf8996e76d93c8458d96d4fa