apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/baha0x13/ticket-sale-api-service
    newTag: a1cc8bbc8095b1b029eb6f5e26ed3dd66144be90
  - name: ghcr.io/baha0x13/ticket-sale-auth-service
    newTag: a1cc8bbc8095b1b029eb6f5e26ed3dd66144be90
  - name: ghcr.io/baha0x13/ticket-sale-movie-service
    newTag: a1cc8bbc8095b1b029eb6f5e26ed3dd66144be90
  - name: ghcr.io/baha0x13/ticket-sale-notifications-service
    newTag: a1cc8bbc8095b1b029eb6f5e26ed3dd66144be90
  - name: ghcr.io/baha0x13/ticket-sale-frontend
    newTag: a1cc8bbc8095b1b029eb6f5e26ed3dd66144be90