apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/baha0x13/ticket-sale-api-service
    newTag: 6e29fd5bf5466eb03d1a2a2a13a917531f0c00f6
  - name: ghcr.io/baha0x13/ticket-sale-auth-service
    newTag: 6e29fd5bf5466eb03d1a2a2a13a917531f0c00f6
  - name: ghcr.io/baha0x13/ticket-sale-movie-service
    newTag: 6e29fd5bf5466eb03d1a2a2a13a917531f0c00f6
  - name: ghcr.io/baha0x13/ticket-sale-notifications-service
    newTag: 6e29fd5bf5466eb03d1a2a2a13a917531f0c00f6
  - name: ghcr.io/baha0x13/ticket-sale-frontend
    newTag: 6e29fd5bf5466eb03d1a2a2a13a917531f0c00f6