apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-service
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
        - name: notifications-service
          image: ghcr.io/baha0x13/ticket-sale-notifications-service:REPLACE_ME
          ports:
            - containerPort: 3001
              name: actuator
          env:
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AMQP_URL
            - name: NOTIFICATIONS_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NOTIFICATIONS_QUEUE
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_PORT
            - name: SMTP_SECURE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_SECURE
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASS
          livenessProbe:
            httpGet:
              path: /healthz
              port: actuator
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /readyz
              port: actuator
            initialDelaySeconds: 5
            periodSeconds: 10