apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
        - name: api-service
          image: ghcr.io/baha0x13/ticket-sale-api-service:REPLACE_ME
          ports:
            - containerPort: 3030
              name: http
          env:
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AMQP_URL
            - name: MOVIES_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MOVIES_QUEUE
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_SERVICE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: FRONTEND_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FRONTEND_ORIGIN

          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15