apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/baha0x13/ticket-sale-api-service
    newTag: 3560a91435279343b5dc4a5d907bf73b76e304de
  - name: ghcr.io/baha0x13/ticket-sale-auth-service
    newTag: 3560a91435279343b5dc4a5d907bf73b76e304de
  - name: ghcr.io/baha0x13/ticket-sale-movie-service
    newTag: 3560a91435279343b5dc4a5d907bf73b76e304de
  - name: ghcr.io/baha0x13/ticket-sale-notifications-service
    newTag: 3560a91435279343b5dc4a5d907bf73b76e304de
  - name: ghcr.io/baha0x13/ticket-sale-frontend
    newTag: 3560a91435279343b5dc4a5d907bf73b76e304de

configMapGenerator:
  - name: app-config
    namespace: app
    behavior: merge
    literals:
      - DB_HOST=aws-0-eu-west-1.pooler.supabase.com
      - DB_PORT=5432
      - API_GATEWAY_URL=http://api.ticket-sale.local
      - FRONTEND_ORIGIN=http://ticket-sale.local

patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ticket-sale
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: ticket-sale.local
      - op: replace
        path: /spec/rules/1/host
        value: api.ticket-sale.local