apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-sale
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/baha0x13/ticket-sale-config.git
    targetRevision: HEAD
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
