apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: monitoring
type: Opaque
stringData:
  DB_HOST: "aws-0-eu-central-1.pooler.supabase.com"
  DB_PORT: "5432"
  DB_USERNAME: "postgres.changeme"
  DB_PASSWORD: "changeme"
  DB_NAME: "postgres"
